export { default as Switch } from './switch/Switch.vue'
export { default as Button } from './button/Button.vue'
export { default as Tabs } from './tabs/Tabs.vue'
export { default as Tab } from './tabs/Tab.vue'
export { default as Dialog } from './dialog/Dialog.vue'
export { show as show } from './dialog/dialogMethod'
